from .abstractwidget import AbstractWidget
from .scale import Scale
from .light import Light
from .reticle import Reticle
from .tank import Tank
from .pumpflow import PumpFlow
from .schedule import Schedule
from .radio import Radio
from .pump import Pump
from .timeline import Timeline
from .simpletext import Simpletext
from .simplehtml import SimpleHTML
from .slider import Slider
from .frame import Frame
from .performancescale import Performancescale
